### ISSUE TITLE
Move deps to devDependencies?

### ISSUE THREAD

**Issue by corwin-of-amber** [andersevenrud/simplejsonconf#1]
Heh.

Sorry for being a nag, but here the reverse problem occurs: all deps are listed as `dependencies`, hence installing this package also installs `webpack` and `@babel/*`, which are quite large.

Seems like they are not needed when consuming the runtime version of this package.

**Comment by andersevenrud** [comment]
Looks like github notification replies was broken yesterday, because my reply obviously did not get here :(

copy/paste:

> Indeed! Feel free to open a PR and I'll merge it ASAP :)
